name: flutter_app1
description: A RSS reader.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+20

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  provider: ^4.3.2
  webfeed: ^0.6.0
  http: ^0.12.2
  flutter_html: ^1.1.1
  shared_preferences: ^0.5.12
  time_formatter: ^1.0.0
  incrementally_loading_listview: ^0.3.0
  url_launcher: ^5.7.10
  share: ^0.6.5+4
  progress_dialog: ^1.2.3
  cached_network_image: ^2.3.3
  transparent_image: ^1.0.0
  flutter_svg: ^0.19.2
  fluttertoast: ^7.1.6
  google_fonts: ^1.1.1
  salomon_bottom_bar: ^2.0.0
  font_awesome_flutter: ^8.10.0
  connectivity: ^2.0.2
  expansion_tile_card: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#   - family: NotoSans
#     fonts:
#       - asset: fonts/NotoSans-Regular.ttf
#       - asset: fonts/NotoSans-Italic.ttf
#         style: italic
#       - asset: fonts/NotoSans-Bold.ttf
#         weight: 700
#       - asset: fonts/NotoSans-BoldItalic.ttf
#         weight: 700
#         style: italic
#       - asset: fonts/NotoSans-Medium.ttf
#         weight: 500
#       - asset: fonts/NotoSans-MediumItalic.ttf
#         weight: 500
#         style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
